# Generated by Django 4.2.3 on 2023-07-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzloo', '0002_alter_musictrack_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='myzloo.musictrack'),
        ),
    ]
