# Generated by Django 4.2.3 on 2023-07-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myzloo', '0004_favorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
