# Generated by Django 4.2.3 on 2023-07-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myzloo', '0007_rename_favorites_myzloo_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorites',
        ),
    ]
