# Generated by Django 4.2.3 on 2023-07-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzloo', '0008_remove_customuser_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='myzloo.musictrack'),
        ),
    ]
