# Generated by Django 4.2.3 on 2023-07-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzloo', '0012_alter_musictrack_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
