# Generated by Django 4.2.3 on 2023-07-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzloo', '0014_alter_customuser_groups_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
