# Generated by Django 4.2.3 on 2023-07-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzloo', '0016_customuser_favorite_tracks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_tracks',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(related_name='users_favorite', through='myzloo.myzloo_favorites', to='myzloo.musictrack'),
        ),
    ]
