# Generated by Django 4.2.3 on 2023-08-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzloo', '0017_remove_customuser_favorite_tracks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
