# Generated by Django 4.2.3 on 2023-08-14 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzloo', '0018_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrack',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='musictrack',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='audio_file',
            field=models.URLField(),
        ),
    ]
